title: Databased & Webpilled
name: Mason Mason
email: MasonTD@hendrix.edu

# The `>` after `description:` means to ignore line-breaks until next key.
# If you want to omit the line-break after the end of text, use `>-` instead.

description: >
  A journal chronicling my journey learning to create in HTML, CSS, and other
  web-based mediums to interact with the coding world on a grander scale.

# Build settings

remote_theme: chesterhow/tale

permalink:    /:year-:month-:day/:title
paginate:     5

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-remote-theme